### ISSUE TITLE
1.3.4 crashing Assassin's Creed 2

### ISSUE THREAD

**Issue by Exhalted** [4lex4nder/ReshadeEffectShaderToggler#41]
It appears that Assassin's Creed 2 is loading up fine on REST 1.3.0 release, but for some reason crashes the game immediately on the latest 1.3.4 release. There's an additional issue where Alt-tabbing out of AC2 will also crash REST 1.3.0 (and the game).

Edit: using REST 1.2.3 no longer crashes the game upon alt-tabbing but the shader selection menu is gone, and have to use numpad again. One workaround is, setting up and marking the shaders in 1.3.0 with UI then replace it with 1.2.3, then the alt tabbing is working fine again and it still retained the marked shaders.

**Comment by 4lex4nder** [comment]
Should be fixed with 1.3.5, can you confirm?

**Comment by Exhalted** [comment]
I tried 1.3.5 and 1.3.6 both, it seems like alt tabbing still crashes the game when alt tabbing back in. 

I also confirmed again that 1.2.3 does not crash when alt tabbing back in, so it seems like anything after 1.2.3 causes crashes when tabbing back into the game.

**Comment by 4lex4nder** [comment]
How about 1.3.14?

**Comment by Exhalted** [comment]
I just tried it, the issue is completely fixed in 1.3.14! Thanks a lot, really! now alt tabbing causes no issues/crashes.
